class RtlPlatformCase {
  const RtlPlatformCase({
    required this.id,
    required this.text,
    required this.direction,
    required this.locale,
  });

  final String id;
  final String text;
  final String direction;
  final String locale;
}

const List<RtlPlatformCase> rtlPlatformCorpus = <RtlPlatformCase>[
  RtlPlatformCase(
    id: 'RTLC-001',
    text: 'السعر 1234 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-002',
    text: 'السعر \$1,234.56 اليوم',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-003',
    text: 'لدي 123 تفاحة',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-004',
    text: 'الوقت 10:45 مساءً',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-005',
    text: 'السعر 1234 ريال',
    direction: 'ltr',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-006',
    text: 'لدي 5 كتب و 10 أقلام',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-007',
    text: 'رقم الهاتف 0501234567',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-008',
    text: 'الفصل 12 من 30',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-009',
    text: 'قیمت 1234 تومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-010',
    text: 'قیمت 1,234.50 دلار',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-011',
    text: 'قیمت 1234 تومان',
    direction: 'ltr',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-012',
    text: 'من 3 برادر دارم',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-013',
    text: 'السعر ١٢٣٤ ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-014',
    text: 'السعر ١٬٢٣٤٫٥٦ ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-015',
    text: 'السعر ١٢٣٤ ريال',
    direction: 'ltr',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-016',
    text: 'لدي ٥ أقلام',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-017',
    text: '١٢٣ و ٤٥٦',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-018',
    text: 'قیمت ۱۲۳۴ تومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-019',
    text: 'قیمت ۱٬۲۳۴٫۵۶ تومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-020',
    text: 'قیمت ۱۲۳۴ تومان',
    direction: 'ltr',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-021',
    text: 'من ۳ کتاب دارم',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-022',
    text: 'מחיר 1234 ₪',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-023',
    text: 'מחיר \$1,234.56 היום',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-024',
    text: 'מחיר 1234 ₪',
    direction: 'ltr',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-025',
    text: 'יש לי 7 ספרים',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-026',
    text: 'מספר הטלפון 050-1234567',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-027',
    text: 'مرحبا ABC 123 DEF',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-028',
    text: 'ABC مرحبا 123 عالم DEF',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-029',
    text: '123 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-030',
    text: 'مرحبا 123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-031',
    text: 'مرحبا (123)',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-032',
    text: 'مرحبا -123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-033',
    text: 'مرحبا +123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-034',
    text: 'مرحبا \$123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-035',
    text: 'مرحبا 123%',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-036',
    text: 'مرحبا 1/2',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-037',
    text: 'مرحبا 12:34',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-038',
    text: 'مرحبا ABC 123 DEF',
    direction: 'ltr',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-039',
    text: '123 مرحبا',
    direction: 'ltr',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-040',
    text: 'بين مرحبا و ABC يوجد 123 عنصر',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-041',
    text: 'Hello 123 مرحبا 456 World',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-042',
    text: 'السعر: 1234!',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-043',
    text: 'السعر، 1234، شكرا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-044',
    text: '“مرحبا 123”',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-045',
    text: 'مرحبا؟ 123.',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-046',
    text: '(مرحبا) 123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-047',
    text: 'مرحبا; 123: أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-048',
    text: 'السعر \u200e1234\u200e ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-049',
    text: 'السعر \u200f1234\u200f ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-050',
    text: 'السعر \u20661234\u2069 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-051',
    text: 'السعر \u20671234\u2069 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-052',
    text: 'السعر \u20681234\u2069 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-053',
    text: '\u20661234\u2069 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-054',
    text: 'مرحبا \u20661234\u2069',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-055',
    text: '\u200fمرحبا \$123\u200f',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-056',
    text: 'السعر \u200e1234\u200e ريال',
    direction: 'ltr',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-057',
    text: '+971 50 123 4567',
    direction: 'ltr',
    locale: 'en',
  ),
  RtlPlatformCase(
    id: 'RTLC-058',
    text: 'اتصل بي على +971 50 123 4567',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-059',
    text: 'هاتفي: +971-50-123-4567',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-060',
    text: '+98 21 1234 5678',
    direction: 'ltr',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-061',
    text: 'تماس بگیرید +98 21 1234 5678',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-062',
    text: 'התקשר אליי +972 50-123-4567',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-063',
    text: 'التاريخ 2026-09-08',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-064',
    text: 'الاجتماع الساعة 14:30',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-065',
    text: 'اليوم 08/09/2026',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-066',
    text: 'من الساعة 9 إلى 5',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-067',
    text: 'تاریخ امروز ۱۴۰۵/۰۶/۱۷',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-068',
    text: 'התאריך היום הוא 08/09/2026',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-069',
    text: 'السعر 1234\nريال فقط',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-070',
    text: 'السطر الأول 111\nالسطر الثاني 222\nالسطر الثالث 333',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-071',
    text: 'מחיר 1234\n₪ בלבד',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-072',
    text: 'قیمت 1234\nتومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(id: 'RTLC-073', text: '1234', direction: 'ltr', locale: 'en'),
  RtlPlatformCase(id: 'RTLC-074', text: '1234', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(id: 'RTLC-075', text: '١٢٣٤', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(id: 'RTLC-076', text: '۱۲۳۴', direction: 'rtl', locale: 'fa'),
  RtlPlatformCase(
    id: 'RTLC-077',
    text: 'مرحبا بالعالم',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-078',
    text: 'שלום עולם',
    direction: 'rtl',
    locale: 'he',
  ),
  RtlPlatformCase(
    id: 'RTLC-079',
    text: 'سلام دنیا',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-080',
    text: '123 مرحبا 456',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-081',
    text: 'مرحبا 123 أهلا 456 وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-082',
    text: '1234 1234',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-083',
    text: 'مرحبا،123،أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-084',
    text: 'مرحباABC123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-085',
    text: '123ABCمرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-086',
    text: 'السعر 1 234 567 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-087',
    text: 'السعر 1\u202f234\u202f567 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-088',
    text: 'قیمت 1 234٫56 تومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(
    id: 'RTLC-089',
    text: 'السعر 1234٫56 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-090',
    text: 'السعر 1٬234٬567 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-091',
    text: 'قیمت 1234 روپے ہے',
    direction: 'rtl',
    locale: 'ur',
  ),
  RtlPlatformCase(
    id: 'RTLC-092',
    text: 'میرے پاس 5 کتابیں ہیں',
    direction: 'rtl',
    locale: 'ur',
  ),
  RtlPlatformCase(
    id: 'RTLC-093',
    text: 'قیمت ۱۲۳۴ روپے',
    direction: 'rtl',
    locale: 'ur',
  ),
  RtlPlatformCase(
    id: 'RTLC-094',
    text: 'فون نمبر +92 300 1234567',
    direction: 'rtl',
    locale: 'ur',
  ),
  RtlPlatformCase(id: 'RTLC-095', text: '123', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-096',
    text: 'مرحبا 123 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-097',
    text: '123 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-098',
    text: 'مرحبا 123',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-099',
    text: 'مرحبا 123 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-100',
    text: 'ABC123مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-101', text: '129', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-102',
    text: 'مرحبا 129 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-103',
    text: '129 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-104',
    text: 'مرحبا 129',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-105',
    text: 'مرحبا 129 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-106',
    text: 'ABC129مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-107', text: '999', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-108',
    text: 'مرحبا 999 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-109',
    text: '999 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-110',
    text: 'مرحبا 999',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-111',
    text: 'مرحبا 999 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-112',
    text: 'ABC999مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-113',
    text: '1,999',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-114',
    text: 'مرحبا 1,999 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-115',
    text: '1,999 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-116',
    text: 'مرحبا 1,999',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-117',
    text: 'مرحبا 1,999 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-118',
    text: 'ABC1,999مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-119', text: '9.99', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-120',
    text: 'مرحبا 9.99 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-121',
    text: '9.99 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-122',
    text: 'مرحبا 9.99',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-123',
    text: 'مرحبا 9.99 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-124',
    text: 'ABC9.99مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-125', text: '-99', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-126',
    text: 'مرحبا -99 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-127',
    text: '-99 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-128',
    text: 'مرحبا -99',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-129',
    text: 'مرحبا -99 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-130',
    text: 'ABC-99مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-131',
    text: '\$999',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-132',
    text: 'مرحبا \$999 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-133',
    text: '\$999 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-134',
    text: 'مرحبا \$999',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-135',
    text: 'مرحبا \$999 أهلا وسهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-136',
    text: 'ABC\$999مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-137',
    text: 'مرحبا ١٢٣ أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-138', text: '١٢٣', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-139',
    text: 'مرحبا ٩٩٩ أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-140', text: '٩٩٩', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-141',
    text: 'قیمت ۱۲۳ تومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(id: 'RTLC-142', text: '۱۲۳', direction: 'rtl', locale: 'fa'),
  RtlPlatformCase(
    id: 'RTLC-143',
    text: 'قیمت ۹۹۹ تومان',
    direction: 'rtl',
    locale: 'fa',
  ),
  RtlPlatformCase(id: 'RTLC-144', text: '۹۹۹', direction: 'rtl', locale: 'fa'),
  RtlPlatformCase(
    id: 'RTLC-145',
    text: 'مرحبا 123 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-146',
    text: 'السعر 99 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-147',
    text: 'السعر 9999 ريال',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-148',
    text: 'مرحبا \$9.99',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-149',
    text: 'مرحبا 9.99 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-150',
    text: 'مرحبا أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-151',
    text: 'مرحبا 123 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-152',
    text: 'ABC 1 مرحبا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-153',
    text: 'מחיר 100 ₪',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-154',
    text: 'قیمت 100 تومان',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-155',
    text: 'مرحبا 1 أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-156', text: '\$1', direction: 'rtl', locale: 'ar'),
  RtlPlatformCase(
    id: 'RTLC-157',
    text: 'מחיר 1 ₪',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-158',
    text: 'قیمت 1 تومان',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-159',
    text: 'مرحبا أهلا',
    direction: 'rtl',
    locale: 'ar',
  ),
  RtlPlatformCase(
    id: 'RTLC-160',
    text: 'مرحبا 123 أهلا',
    direction: 'ltr',
    locale: 'ar',
  ),
  RtlPlatformCase(id: 'RTLC-161', text: '999', direction: 'ltr', locale: 'en'),
  RtlPlatformCase(id: 'RTLC-162', text: '999', direction: 'rtl', locale: 'ar'),
];
