/** Values beyond the upstream corpus, chosen to stress segmentation, IDs and the diff bounds. */
export const EXTRA_VALUES: string[] = [
  "",
  " ",
  "  ",
  "a",
  "hello",
  "hello ",
  " hello",
  " hello world ",
  "hello  world",
  "hello, world!",
  "don't stop",
  "can't won't isn't",
  "e-mail re-enter COVID-19",
  "$1,234.56",
  "€1.234,56 total",
  "-42 and +7",
  "100% done",
  "(555) 123-4567",
  "1.5 → 2.5",
  "naïve café",
  "é é",
  "😀",
  "😀😀",
  "hi 👋🏽 there",
  "👨‍👩‍👧‍👦 family",
  "🇬🇧 flag 🇺🇸",
  "مرحبا بالعالم",
  "שלום עולם",
  "नमस्ते दुनिया",
  "こんにちは 世界",
  "你好世界",
  "สวัสดี ชาวโลก",
  "Hello\nWorld",
  "Hello\n\nWorld",
  "\nleading",
  "trailing\n",
  "a\nb\nc",
  "line one\nline two",
  "hello world",
  "tab\tsep",
  "hello hello hello",
  "aaa aaa aaa",
  "abc-def_ghi",
  "user@example.com",
  "https://example.com/path?q=1",
  "1st 2nd 3rd",
  "3.14159",
  "1,000,000",
  "1'000'000",
  "1 000 000",
  "-0.5",
  "$-5",
  "5%",
  "Total: $12.50",
  "x²+y²",
  "A.B.C.",
  "…",
  "​",
  "ｈｅｌｌｏ",
  "İstanbul",
  "straße",
  "ﬁne",
  "a‍b",
  "🏳️‍🌈 pride",
  "word,word",
  "one,two three",
];

export const EXTRA_CHAINS: Record<string, string[]> = {
  "empty in/out": ["hello", "", "hello"],
  "space only": ["a b", " ", "a b"],
  "single char cycle": ["a", "b", "a", "ab", "a"],
  "word to chars": ["hello", "help", "helper", "hello"],
  "repeat words": ["hello hello", "hello", "hello hello hello"],
  "similar words": ["Copy", "Copied", "Copy", "Copying"],
  "punctuated": ["hello, world", "hello world", "hello, world!"],
  "digits inside": ["COVID-19 update", "COVID-20 update", "COVID-19"],
  "money": ["$1,234.56", "$1,235.00", "$999.99", "$10,000.00"],
  "negatives": ["-5", "5", "-5", "-15", "15"],
  "decimals": ["1.5", "1.25", "1.255", "1.2", "1"],
  "grouping grows": ["999", "1,000", "9,999", "10,000", "999,999", "1,000,000"],
  "percent": ["10%", "100%", "1%", "0%"],
  "mixed": ["Total 12 items", "Total 13 items", "Total 130 items", "Total 1,300 items"],
  "two numbers": ["1 of 10", "2 of 10", "2 of 11", "10 of 11"],
  "newline growth": ["a", "a\nb", "a\nb\nc", "a\nc", "c"],
  "newline move": ["hello world", "hello\nworld", "world\nhello", "world hello"],
  "reorder many": ["a b c d e", "e d c b a", "c a e b d"],
  "long replace": ["the quick brown fox jumps over the lazy dog", "pack my box with five dozen liquor jugs", "the quick brown fox jumps over the lazy dog"],
  "emoji": ["😀 hi", "😃 hi", "hi 😃", "😀😃 hi"],
  "rtl": ["مرحبا", "مرحبا بالعالم", "بالعالم", "مرحبا"],
  "nbsp inside": ["a b", "a b", "a b"],
  "leading trailing spaces": [" a ", "a", " a", "a ", "  a  "],
  "words to number": ["ten", "10", "10 ten", "ten 10"],
  "number to word": ["10", "ten", "1", "one"],
  "surrogate split": ["a😀b", "a😀c", "😀", "b😀"],
  "combining": ["café", "cafe", "café ok"],
  "case change": ["Hello World", "hello world", "HELLO WORLD"],
  "grow": ["a", "ab", "abc", "abcd", "abcde", "abcdef"],
  "shrink": ["abcdef", "abcde", "abcd", "abc", "ab", "a"],
  "typing sentence": ["t", "th", "the", "the ", "the q", "the qu", "the quick"],
  "id collision": ["a a a", "a a", "a a a a"],
  "tilde ids": ["abc~1", "abc", "abc~1 abc"],
  "colon ids": ["ab:1", "ab", "ab:0"],
};
